### ISSUE TITLE
Version 7.x

### ISSUE THREAD

**Issue by wucherpfennig** [thecodingmachine/gotenberg-php-client#27]
Do you plan to port this client to version 7.x?

https://github.com/gotenberg/gotenberg/releases

BR wucherpfennig

**Comment by gulien** [comment]
Hello @wucherpfennig 

I'm currently working on stabilizing the v7 version and also adding new features. Once I've got more time, I'll try to upgrade this library 👍

**Comment by geoff-ellison** [comment]
+1 
@gulien this is great! Hope to see v7 compatibility soon.

**Comment by will2877** [comment]
+1
Would have been good to update this before you drop the support for the old versions...
Let me know if you need some help!

**Comment by gulien** [comment]
Hello folks 👋 

Thank you for your interest!

The API primarily consists of `multipart/form-data` endpoints, so this client is mainly a `multipart/form-data` request builder.

Honestly, I'm not sure that using an SDK is required to interact with Gotenberg; it helps a bit, but you might have more flexibility by directly creating "native" multipart/form-data requests in your application.

Anyway, if an SDK makes sense in your case, you may either:

* Create your repository (and add it to the [awesome-list](https://github.com/gotenberg/awesome-gotenberg) 😎 )
* Update this repository (PRs welcome!)

IMO the key will be to mimic the module's organization from Gotenberg (i.e., endpoints per module).

**Comment by gulien** [comment]
https://github.com/gotenberg/gotenberg-php 👀
