### ISSUE TITLE
Helpers to generate pdf directly from html string

### ISSUE THREAD

**Issue by tigitz** [thecodingmachine/gotenberg-php-client#5]
## Expected Behavior
Helpers to generate pdf directly from html string

## Current Behavior
Helpers only exists to generate from a file 

## Possible Solution
`DocumentFactory::makeFromString(string $fileName, string $html)`

```php
public static function makeFromString(string $fileName, string $htmlContent): Document
    {
        $stream = fopen('php://temp','r+');
        fwrite($stream, $html);
        
        return new Document($fileName, stream_for($stream));
    }
```

## Context
Using a templating engine to produce the html, requiring to retrieve the html from a file through `DocumentFactory::makeFromPath(string $html)` would imply an unnecessary I/O operation to store the html on the hard drive and reload it from it while you already have the html content in php memory.

I can make a PR if solution seems fine to you

**Comment by gulien** [comment]
Hello! Of course, feel free to open a PR for this feature 👍
